
language: java
jdk: oraclejdk8

install:
  - nvm install 7.7.1
  - npm install

branches:
  only:
    - master
script:
  - cd appname-backend
  - ./gradlew bootRepackage

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - appname-frontend/node_modules

